# Generated by Django 5.1.4 on 2025-01-01 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_city_customuser_country_and_more'),
        ('account', 'fix_cv_link'),
    ]

    operations = [
        migrations.RunPython(
            code=lambda apps, schema_editor: None,
            reverse_code=lambda apps, schema_editor: None,
        ),
    ]
