# Generated by Django 5.1.4 on 2025-02-19 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_merge_20250101_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('employer', 'Employer'), ('employee', 'Job Seeker'), ('admin', 'Administrator')], max_length=10),
        ),
    ]
