# Generated by Django 5.1.4 on 2024-12-28 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_alter_applicant_options_applicant_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='job',
            name='type',
        ),
    ]
