# Generated by Django 5.1.4 on 2025-02-20 02:17

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0004_job_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description'),
        ),
    ]
