# Generated by Django 5.1.4 on 2025-02-20 02:23

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0005_alter_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Company Description'),
        ),
    ]
